version: 1.0.12.{build}
os: Visual Studio 2015
configuration: CI

nuget:
  account_feed: true
  project_feed: true

before_build:
- cmd: nuget restore DocsByReflection.sln

build:
  project: DocsByReflection.sln
  verbosity: normal

after_build:
- cmd: >-
    mkdir .\src\nuget

    nuget pack .\DocsByReflection\DocsByReflection.csproj -IncludeReferencedProjects -Version %APPVEYOR_BUILD_VERSION% -OutputDirectory .\nuget

artifacts:
  - path: .\nuget\*.nupkg
    name: NuGet packages
