version: 1.0.12.{build}
os: Visual Studio 2015
configuration: CI

nuget:
  account_feed: true
  project_feed: true

before_build:
- cmd: nuget restore DocsByReflection.sln

build:
  project: DocsByReflection.sln
  verbosity: normal
